In [ ]:
import numpy as np
import pandas as pd

# Numpy

### Ejercicio arrays

1. Crear un array `array_1` de dimensión 6 filas y 4 columnas
2. Crear un array `array_2` cambiando las dimensiones a 3 filas y 8 columnas
3. Crear un array `array_3` cambiando las dimensiones a 5 filas y 7 columnas
4. Crear un array `array_4` de zeros y otro de unos de dimension 2 filas, 3 columnas

In [ ]:
# Paso 1: Crear un Array `array_1` de Dimensión 6 Filas y 4 Columnas
array_1 = np.random.randint(0, 100, (6, 4))
print(array_1)

# Paso 2: Crear un Array `array_2` Cambiando las Dimensiones a 3 Filas y 8 Columnas
array_2 = np.random.randint(0, 50, (3, 8))
print(array_2)

# Paso 3: Crear un Array `array_3` Cambiando las Dimensiones a 5 Filas y 7 Columnas
array_3 = np.random.randint(0,600,(5,7))
print(array_3)

# Paso 4: Crear un Array `array_4` de Zeros y Otro de Unos de Dimensión 2 Filas y 3 Columnas
array_4 = np.random.randint(0,500,(2,3))
print(array_4)

[[30 89 97 64]
 [71 26 75 65]
 [76 85 40 36]
 [ 4 96 18 63]
 [ 4 59 70 55]
 [29 91 42 51]]
[[ 4 12 13 39  7 41 25 35]
 [13 42 10 45 25 11 49 26]
 [10 11 15 45 26  7  5 11]]
[[426 395 198 224  20  36  77]
 [386  60 198 405 536  28 255]
 [445 224 558 343 227 161 503]
 [457  44 541 435 302 591 350]
 [451 568 325 477 101 385  21]]
[[313 332 241]
 [128 402 441]]


## Ejercicio numpy

Imagina que tienes datos de temperatura promedio diaria de una ciudad durante un mes (30 días). Quieres realizar un análisis básico de estos datos usando Numpy para obtener información útil como la temperatura promedio del mes, la temperatura máxima y mínima, y los días en los que la temperatura estuvo por encima de la temperatura promedio.

1. **Crear un array de temperaturas:**

  - Genera un array de Numpy con 30 elementos que representen las temperaturas promedio diarias de la ciudad durante un mes.
  - Que se genere con numeros enteros aleatorios, entre los valores 18 y 29

2. **Calcular estadísticas básicas:**

  - Calcula la temperatura promedio del mes.
  - Encuentra la temperatura máxima y mínima del mes.

3. **Identificar días calurosos:**

  - Identifica los días en los que la temperatura estuvo por encima de la temperatura promedio del mes.

4. **Imprimir resultados:**

  - Imprime la temperatura promedio, máxima y mínima.
  - Imprime los índices (días) en los que la temperatura estuvo por encima del promedio.

In [ ]:
temperaturas_mes = np.random.randint(18,29,size=30)
print(temperaturas_mes)

# Paso 2: Calcular estadísticas básicas
promedio = np.mean(temperaturas_mes)
print(" La temperatura promedio del mes es de {:.1f} grados".format(promedio))

# Paso 3: Identificar días calurosos
maximo = np.max(temperaturas_mes)
minimo = np.min(temperaturas_mes)
print(f" El día mas caluroso tuvo {maximo} grados de maxima")
print(f" El día mas frio tuvo {minimo} grados de minima")

# np.where para encontrar los índices de los días en que la temperatura estuvo por encima del promedio
mayor_promedio = np.where(temperaturas_mes > promedio) [0] +1
print(f" Los días más calurosos del mes fueron {mayor_promedio}")



[26 28 21 27 24 26 25 26 28 20 21 25 23 21 22 25 22 19 25 19 25 26 23 18
 28 18 19 18 28 27]
 La temperatura promedio del mes es de 23.4 grados
 El día mas caluroso tuvo 28 grados de maxima
 El día mas frio tuvo 18 grados de minima
 Los días más calurosos del mes fueron [ 1  2  4  5  6  7  8  9 12 16 19 21 22 25 29 30]


# Pandas

### Ejercicio pandas

1. Sobre nuestro dataframe "df" crea nuevas columnas:
  - **"age_menos_20":** resultado de restarle 20 años al campo 'edad'
  - **"age_mas_10":** resultado de sumarle 10 años al campo 'edad'
  - **"annual_salary_entre_1000":** resultado de dividir el salario anual entre 1000
  - **"salario_mensual":** resultado de dividir el salario anual entre 12
  - **"edad_respecto_media":** a partir del campo 'Gender', generar otro campo tal que si la edad es mayor que la media se informe con 'Mayor que la media' y si es menor se informe con 'Menor que la media'
  
2. Guarda en una variable de tipo lista los nombres de las columnas y muestra el valor de la variable

3.  Muestra las 20 ultimas filas

4. Elimina las columnas 'age_menos_20' y 'annual_salary_entre_1000' del dataframe 'df'

5. Muestra las 8 primeras filas

6. Crea un nuevo dataframe llamado 'df_2' que no tenga el campo 'age_mas_10' (pero mantenga los campos que teníamos en 'df' hasta el punto 8)

7. Muestra la forma de este nuevo df_2, un resumen de su información y la información estadística de este campo

8. Genera la matriz de correlación y obtén alguna conclusión entre las siguientes variables:
  - Age, AnnualSalary, Purchased

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/car_data.csv')

In [ ]:
# Crea una nueva columna como resultado de restarle 20 años al campo 'edad'
df ["age_menos_20"] = df["Age"] - 20

# Crea una nueva columna como resultado de sumarle 10 años al campo 'edad'
df ["age_mas_10"] = df["Age"] + 10

# Crea una nueva columna como resultado de dividir el salario anual entre 1000
df ["Annual_salary_1000"] = df["AnnualSalary"] / 1000

# Crea una nueva columna como resultado de dividir el salario anual entre 12
df ["Annual_salary_12"] = (df["AnnualSalary"] / 12).astype(float).round(2)

# Crear la nueva columna usando np.where
df ["age_mas_10"] = np.where(df["age_mas_10"] >=50, df["age_mas_10"] -9,0)
df.head(10)



User ID  Gender  Age  AnnualSalary  Purchased  age_menos_20  age_mas_10  \
0      385    Male   35         20000          0            15           0   
1      681    Male   40         43500          0            20          41   
2      353    Male   49         74000          0            29          50   
3      895    Male   40        107500          1            20          41   
4      661    Male   25         79000          0             5           0   
5      846  Female   47         33500          1            27          48   
6      219  Female   46        132500          1            26          47   
7      588    Male   42         64000          0            22          43   
8       85  Female   30         84500          0            10           0   
9      465    Male   41         52000          0            21          42   

   Annual_salary_1000  Annual_salary_12  
0                20.0           1666.67  
1                43.5           3625.00  
2                74.0           6166.67  
3               107.5           8958.33  
4                79.0           6583.33  
5                33.5           2791.67  
6               132.5          11041.67  
7                64.0           5333.33  
8                84.5           7041.67  
9                52.0           4333.33

In [ ]:
# 2. Guarda en una variable de tipo lista los nombres de las columnas y muestra el valor de la variable
columnas = df.columns[:]
columnas_lista = [df.columns[:]]

print(len(columnas))
print(len(columnas_lista))

9
1


In [ ]:
# 3.  Muestra las 20 ultimas filas
df.tail(20)

User ID  Gender  Age  AnnualSalary  Purchased  age_menos_20  age_mas_10  \
980       82  Female   46         23500          1            26          47   
981      695  Female   39         79000          0            19           0   
982      946    Male   39         60500          0            19           0   
983      676    Male   42         54000          0            22          43   
984      649  Female   28         87000          0             8           0   
985      477  Female   45         77500          0            25          46   
986      572    Male   48         33000          1            28          49   
987      832  Female   31         71000          0            11           0   
988      302    Male   33        121500          1            13           0   
989      420  Female   27         84000          0             7           0   
990      971    Male   25         56500          0             5           0   
991      382  Female   30         48500          0            10           0   
992      168  Female   24         67500          0             4           0   
993      476  Female   54        136500          0            34          55   
994      951  Female   53        104000          1            33          54   
995      863    Male   38         59000          0            18           0   
996      800  Female   47         23500          0            27          48   
997      407  Female   28        138500          1             8           0   
998      299  Female   48        134000          1            28          49   
999      687  Female   44         73500          0            24          45   

     Annual_salary_1000  Annual_salary_12  
980                23.5           1958.33  
981                79.0           6583.33  
982                60.5           5041.67  
983                54.0           4500.00  
984                87.0           7250.00  
985                77.5           6458.33  
986                33.0           2750.00  
987                71.0           5916.67  
988               121.5          10125.00  
989                84.0           7000.00  
990                56.5           4708.33  
991                48.5           4041.67  
992                67.5           5625.00  
993               136.5          11375.00  
994               104.0           8666.67  
995                59.0           4916.67  
996                23.5           1958.33  
997               138.5          11541.67  
998               134.0          11166.67  
999                73.5           6125.00

In [ ]:
# 4. Elimina las columnas 'age_menos_20' y 'annual_salary_entre_1000' del dataframe 'df'
df_2 = df.drop('age_menos_20', axis=1).drop('Annual_salary_1000', axis=1)
df_2.head()




User ID Gender  Age  AnnualSalary  Purchased  age_mas_10  Annual_salary_12
0      385   Male   35         20000          0           0           1666.67
1      681   Male   40         43500          0          41           3625.00
2      353   Male   49         74000          0          50           6166.67
3      895   Male   40        107500          1          41           8958.33
4      661   Male   25         79000          0           0           6583.33

In [ ]:
# 5. Muestra las 8 primeras filas
df.head(8)

User ID  Gender  Age  AnnualSalary  Purchased  age_menos_20  age_mas_10  \
0      385    Male   35         20000          0            15           0   
1      681    Male   40         43500          0            20          41   
2      353    Male   49         74000          0            29          50   
3      895    Male   40        107500          1            20          41   
4      661    Male   25         79000          0             5           0   
5      846  Female   47         33500          1            27          48   
6      219  Female   46        132500          1            26          47   
7      588    Male   42         64000          0            22          43   

   Annual_salary_1000  Annual_salary_12  
0                20.0           1666.67  
1                43.5           3625.00  
2                74.0           6166.67  
3               107.5           8958.33  
4                79.0           6583.33  
5                33.5           2791.67  
6               132.5          11041.67  
7                64.0           5333.33

In [ ]:
# 6. Crea un nuevo dataframe llamado 'df_2' que no tenga el campo 'age_mas_10'
# (pero mantenga los campos que teníamos en 'df' hasta el punto 8)
df_2.head()

User ID Gender  Age  AnnualSalary  Purchased  age_mas_10  Annual_salary_12
0      385   Male   35         20000          0           0           1666.67
1      681   Male   40         43500          0          41           3625.00
2      353   Male   49         74000          0          50           6166.67
3      895   Male   40        107500          1          41           8958.33
4      661   Male   25         79000          0           0           6583.33

In [ ]:
# 7. Muestra la forma de este nuevo df_2, un resumen de su información y la información estadística de este campo
df.describe()
df.info()
df.head(20)

User ID  Gender  Age  AnnualSalary  Purchased  age_menos_20  age_mas_10  \
0       385    Male   35         20000          0            15           0   
1       681    Male   40         43500          0            20          41   
2       353    Male   49         74000          0            29          50   
3       895    Male   40        107500          1            20          41   
4       661    Male   25         79000          0             5           0   
5       846  Female   47         33500          1            27          48   
6       219  Female   46        132500          1            26          47   
7       588    Male   42         64000          0            22          43   
8        85  Female   30         84500          0            10           0   
9       465    Male   41         52000          0            21          42   
10      686    Male   42         80000          0            22          43   
11      408    Male   47         23000          1            27          48   
12      790  Female   32         72500          0            12           0   
13      116  Female   27         57000          0             7           0   
14      118  Female   42        108000          1            22          43   
15       54  Female   33        149000          1            13           0   
16       90    Male   35         75000          0            15           0   
17      372    Male   35         53000          0            15           0   
18      926    Male   46         79000          1            26          47   
19       94  Female   39        134000          1            19           0   

    Annual_salary_1000  Annual_salary_12  
0                 20.0           1666.67  
1                 43.5           3625.00  
2                 74.0           6166.67  
3                107.5           8958.33  
4                 79.0           6583.33  
5                 33.5           2791.67  
6                132.5          11041.67  
7                 64.0           5333.33  
8                 84.5           7041.67  
9                 52.0           4333.33  
10                80.0           6666.67  
11                23.0           1916.67  
12                72.5           6041.67  
13                57.0           4750.00  
14               108.0           9000.00  
15               149.0          12416.67  
16                75.0           6250.00  
17                53.0           4416.67  
18                79.0           6583.33  
19               134.0          11166.67

In [ ]:
# 8. Genera la matriz de correlación y obtén alguna conclusión entre las siguientes variables
df[["Age", "AnnualSalary", "Purchased"]].corr()

print("""Con los siguientes datos, podemos observar que la correlación entre edad y compra es positiva y moderadamente fuerte
         (0.,62) por lo que podríamos decir que a mayor edad, mayor frecuencia de compra pudiendo deberse a que las personas con mayor
         edad cuentan con mayor estabilidad financiera. \n Por otro lado observamos que la correlación entre la edad y el salario es levemente
         positiva (0.17), contra todo pronóstico, a mayor edad no se obtiene un mayor sueldo pudiendo deberse a que una subida salarial
         puede estar mas relacionada con la educación\n Por último, los datos arrojados nos dicen que la correlación entre salario y compra es
         positiva pero de manera leve (0,36) con lo que podríamos decir que a mayor salario no se realizan mayores compras habiendo otros factores
         que influyen mas en la decisión de compra""")


Con los siguientes datos, podemos observar que la correlación entre edad y compra es positiva y moderadamente fuerte
         (0.,62) por lo que podríamos decir que a mayor edad, mayor frecuencia de compra pudiendo deberse a que las personas con mayor
         edad cuentan con mayor estabilidad financiera. 
 Por otro lado observamos que la correlación entre la edad y el salario es levemente
         positiva (0.17), contra todo pronóstico, a mayor edad no se obtiene un mayor sueldo pudiendo deberse a que una subida salarial
         puede estar mas relacionada con la educación
 Por último, los datos arrojados nos dicen que la correlación entre salario y compra es
         positiva pero de manera leve (0,36) con lo que podríamos decir que a mayor salario no se realizan mayores compras habiendo otros factores
         que influyen mas en la decisión de compra


### Ejercicio rename

1. Cambia el nombre de las siguientes columnas sobre el df 'df_renamed'

- Age -> edad
- AnnualSalary -> salario_anual
- Purchased -> comprado

In [ ]:
# Age -> edad
# AnnualSalary -> salario_anual
# Purchased -> comprado

df = df.rename(columns={'Age':'edad'}).rename(columns={'AnnualSalary':'salario_anual'}).rename(columns={'Purchased':'comprado'})
df.head()


User ID Gender  Age  AnnualSalary  Purchased  age_menos_20  age_mas_10  \
0      385   Male   35         20000          0            15           0   
1      681   Male   40         43500          0            20          41   
2      353   Male   49         74000          0            29          50   
3      895   Male   40        107500          1            20          41   
4      661   Male   25         79000          0             5           0   

   Annual_salary_1000  Annual_salary_12  
0                20.0           1666.67  
1                43.5           3625.00  
2                74.0           6166.67  
3               107.5           8958.33  
4                79.0           6583.33

### Ejercicio filter

1. df_filtrado_1: edad mayor que 30 años, salario menor a 100.000 y género ha de ser female

2. df_filtrado_2: salario menor que 100.000, edad mayor o igual a 45 y ordenar por su edad de mayor a menor

3. df_filtrado_3: que hayan realizado alguna compra, que sean 'male', que tengan más de 30 años pero menos de 50 y que su salario sea mayor a 100.000, ordenados por edad (de menor a mayor) y salario (de mayor a menor)

In [ ]:
# 1. Edad mayor que 30 años, salario menor a 100.000 y género ha de ser female
df_filtrado_1 = df[(df['Age'] > 30)&(df['AnnualSalary'] < 100000)&(df['Gender'] == 'Female')]
df_filtrado_1.head()

User ID  Gender  Age  AnnualSalary  Purchased  age_menos_20  age_mas_10  \
5       846  Female   47         33500          1            27          48   
12      790  Female   32         72500          0            12           0   
20      338  Female   39         51500          0            19           0   
21      134  Female   49         39000          1            29          50   
23      294  Female   41         61500          0            21          42   

    Annual_salary_1000  Annual_salary_12  
5                 33.5           2791.67  
12                72.5           6041.67  
20                51.5           4291.67  
21                39.0           3250.00  
23                61.5           5125.00

In [ ]:
# 2. Salario menor que 100.000, edad mayor o igual a 45 y ordenar por su edad de mayor a menor
df_filtrado_2 = df[(df['AnnualSalary'] < 100000)&(df['Age'] >= 45)]
df_filtrado_2 = df_filtrado_2.sort_values(by = 'Age',ascending=True)
df_filtrado_2.head()

User ID  Gender  Age  AnnualSalary  Purchased  age_menos_20  age_mas_10  \
30       273    Male   45         26000          1            25          46   
70       230  Female   45         40500          0            25          46   
96       960    Male   45         75500          1            25          46   
243      196    Male   45         66500          0            25          46   
208      935    Male   45         32000          1            25          46   

     Annual_salary_1000  Annual_salary_12  
30                 26.0           2166.67  
70                 40.5           3375.00  
96                 75.5           6291.67  
243                66.5           5541.67  
208                32.0           2666.67

In [ ]:
# 3. Que hayan realizado alguna compra, que sean 'male', que tengan más de 30 años pero menos de 50 y que su salario sea mayor a 100.000
# ordenados por edad y salario
df_filtrado_3 = df[(df['Purchased'] >=1) & (df['Gender'] == 'Male') & (df['Age'].between(30,49)) & (df['AnnualSalary'] > 100000)]
df_filtrado_3 = df_filtrado_3.sort_values(by=['Age','AnnualSalary'],ascending=[True,False])
df_filtrado_3.head()

User ID Gender  Age  AnnualSalary  Purchased  age_menos_20  age_mas_10  \
234      569   Male   30        149500          1            10           0   
160      957   Male   30        135000          1            10           0   
120      972   Male   30        107000          1            10           0   
164       42   Male   31        136500          1            11           0   
882      451   Male   31        108500          1            11           0   

     Annual_salary_1000  Annual_salary_12  
234               149.5          12458.33  
160               135.0          11250.00  
120               107.0           8916.67  
164               136.5          11375.00  
882               108.5           9041.67

### Ejercicio group by

1. Agrupar por `Product` y `Region`, y obtener la suma de las ventas
2. Filtrar el df para incluir solo aquellos productos donde las ventas son mayores que 1000, agrupar por `Product`, y obtener el promedio de las ventas para cada producto
3. Agrupar por `Region`, y obtener la suma de las ventas y el número total de ventas
4. Filtrar el df para incluir solo aquellas regiones donde la suma de ventas es mayor que 2000, agrupar por `Region`, y obtener la suma y el promedio de las ventas para cada región (usar lambda!!!)

In [ ]:
# Crear el df de ejemplo
data = {
    'Product': ['A', 'B', 'A', 'C', 'B', 'C', 'A', 'B', 'C', 'A'],
    'Region': ['North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': [1000, 1500, 800, 1200, 900, 1100, 750, 1300, 850, 950]
}

df = pd.DataFrame(data)
df.head(5)

Product Region  Sales
0       A  North   1000
1       B  South   1500
2       A   East    800
3       C   West   1200
4       B  North    900

In [ ]:

# 1: Agrupar por `Product` y `Region`, y obtener la suma de las ventas.

grupo_1 = df.groupby(['Product','Region'])['Sales'].sum().reset_index()
print(grupo_1)

# 2: Filtrar el df para incluir solo aquellos productos donde las ventas son mayores que 1000,
# agrupar por `Product`, y obtener el promedio de las ventas para cada producto.
df_6 = pd.DataFrame(grupo_1)
df_6.head(9)

df_filtrado_6 = df_6[df_6['Sales'] > 1000]
df_filtrado_6.head(10)

df_filtrado_6 = df_filtrado_6.groupby(['Product'])['Sales'].mean()
df_filtrado_6.head()

# 3: Agrupar por `Region`, y obtener la suma de las ventas y el número total de ventas.
df_7 = df_6.groupby(['Region'])['Sales'].mean().round(2)
total_ventas = df_7.count()
print(f"\nEl total de ventas es de {total_ventas}:")
df_7.head()

# 4: Filtrar el df para incluir solo aquellas regiones donde la suma de ventas es mayor que 2000,
# agrupar por `Region`, y obtener la suma y el promedio de las ventas para cada región.
df_8_nada = df_6[df_6['Sales'] > 2000].groupby(['Region']).agg({'Sales': ['sum','mean']}).reset_index().round(2)
df_8_algo = df_6[df_6['Sales'] < 2000].groupby(['Region']).agg({'Sales': ['sum','mean']}).reset_index().round(2)
df_8_nada.head()
df_8_algo.head()


  Product Region  Sales
0       A   East   1550
1       A  North   1000
2       A  South    950
3       B  North    900
4       B  South   1500
5       B   West   1300
6       C  North    850
7       C  South   1100
8       C   West   1200

El total de ventas es de 4:


Region Sales         
           sum     mean
0   East  1550  1550.00
1  North  2750   916.67
2  South  3550  1183.33
3   West  2500  1250.00

### Ejercicio pivot & crosstab (opcional)

Tenemos un df que contiene información sobre las compras realizadas por los usuarios en una tienda en línea. Las columnas son las siguientes:

- **User ID:** Identificador único del usuario
- **Gender:** Género del usuario (Male/Female)
- **Age:** Edad del usuario
- **Product Category:** Categoría del producto comprado (Electronics, Clothing, Home, etc.)
- **Purchase Amount:** Monto de la compra

Tenemos que:

1. Crear una tabla dinámica que muestre el monto *total* de las compras por edad y categoría de producto
  - ¿Qué categorías de productos son las más compradas en cada grupo de edad?

2. Crear una tabla de contingencia que muestre la frecuencia de compras por Gender y Product Category.

In [ ]:
import pandas as pd
import numpy as np

# Crear el DataFrame de ejemplo
data = {
    'User ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female', 'Male', 'Male', 'Female', 'Male', 'Female'],
    'Age': [23, 25, 31, 23, 40, 27, 30, 27, 40, 24],
    'Product Category': ['Electronics', 'Clothing', 'Clothing', 'Home', 'Electronics', 'Home', 'Clothing', 'Home', 'Electronics', 'Clothing'],
    'Purchase Amount': [150, 200, 100, 50, 300, 75, 60, 45, 400, 80]
}

df = pd.DataFrame(data)
df


User ID  Gender  Age Product Category  Purchase Amount
0        1    Male   23      Electronics              150
1        2  Female   25         Clothing              200
2        3  Female   31         Clothing              100
3        4    Male   23             Home               50
4        5  Female   40      Electronics              300
5        6    Male   27             Home               75
6        7    Male   30         Clothing               60
7        8  Female   27             Home               45
8        9    Male   40      Electronics              400
9       10  Female   24         Clothing               80

In [ ]:
# Crear la tabla dinámica
tabla_dinamica = pd.pivot_table(df, values = 'Purchase Amount', index = ['Age'], columns = ['Product Category'])
print("La tabla dinámica sería la siguiente: \n {}".format(tabla_dinamica))

La tabla dinámica sería la siguiente: 
 Product Category  Clothing  Electronics  Home
Age                                          
23                     NaN        150.0  50.0
24                    80.0          NaN   NaN
25                   200.0          NaN   NaN
27                     NaN          NaN  60.0
30                    60.0          NaN   NaN
31                   100.0          NaN   NaN
40                     NaN        350.0   NaN


In [ ]:
# Encontrar la categoría de productos más comprada en cada grupo de edad
tabla_dinamica = pd.pivot_table(df, values = 'Purchase Amount', index = ['Age'], columns = ['Product Category'], aggfunc = 'sum')
categoria_mas_comprada = tabla_dinamica.idxmax(axis=1)
print("La categoria mas comprada por edad sería la siguiente: \n {}".format(categoria_mas_comprada))

La categoria mas comprada por edad sería la siguiente: 
 Age
23    Electronics
24       Clothing
25       Clothing
27           Home
30       Clothing
31       Clothing
40    Electronics
dtype: object


In [ ]:
# Crear la tabla de contingencia
tabla_contingencia = pd.crosstab(df['Age'], df['Product Category'], values=df['Purchase Amount'], aggfunc='sum')
print("La tabla de contingencia sería la siguiente: \n \n  {}".format(categoria_mas_comprada))

La tabla de contingencia sería la siguiente: 
 
  Age
23    Electronics
24       Clothing
25       Clothing
27           Home
30       Clothing
31       Clothing
40    Electronics
dtype: object


In [ ]:
# Encontrar la categoría de productos más popular entre hombres y mujeres
Categoria_producto = pd.crosstab(df['Gender'], df['Product Category'], values=df['Purchase Amount'], aggfunc='sum')
print("La categoria de producto mas comprada según el género sería: \n \n  {}".format(Categoria_producto))

La categoria de producto mas comprada según el género sería: 
 
  Product Category  Clothing  Electronics  Home
Gender                                       
Female                 380          300    45
Male                    60          550   125


# Ejercicio Streaming

1. Eliminar las columnas con información de id de sesiones, id de dispositivos, lenguaje, localización, calidad de playback y cantidad de interacciones
2. Genero preferido por los hombres
3. Corroborar si los smartphones son el dispositivo en el cual permanecen más tiempo los usuarios mirando streaming
4. Las edades que suelen pagar más Premium
5. El video que tiene más tiempo de reproducción
6. El género que más le gustó a las mujeres (rating)


Una vez realizados los apartados, redactar conclusiones que podríamos obtener de los datos. Como analistas, es importante que los datos sepamos entenderlos y sacar insights de los mismos. Podemos crear hipótesis si no tenemos evidencia suficiente para reflejar X cosa como hecho verídico.

Recurso: streaming.csv

In [1]:
import pandas as pd

import io
# Subimos el archivo a nuestro proyecto
from google.colab import files
uploaded = files.upload()


Saving streaming.csv to streaming.csv


In [209]:
df = pd.read_csv(io.BytesIO(uploaded['streaming.csv']))

#Eliminar las columnas con información de id de sesiones, id de dispositivos,
#lenguaje, localización, calidad de playback y cantidad de interacciones
df = df.drop(['Session_ID','Languages','User_ID','Location','Playback_Quality','Interaction_Events'], axis=1)
df.head()

#Genero preferido por los hombres
df_genero = pd.crosstab(df['Gender'],df['Genre'],values=df['Genre'], aggfunc='count')
df_genero.head()

max_male = df_genero.loc['Male'].max()
print("El género preferido por los hombres en esta muestra son los documentales con un total de {}".format(max_male))

#Corroborar si los smartphones son el dispositivo en el cual permanecen más tiempo los usuarios mirando streaming
df = df.rename(columns={'Duration_Watched (minutes)' : 'duración_vistas'})
df.colums = df.columns.str.strip()

df_agrupado_1 = df.groupby("Device_Type")["duración_vistas"].sum().round(2)
dispositivo_max = df_agrupado_1.idxmax()
tiempo_maximo = df_agrupado_1.max()
tiempo_maximo_2 = tiempo_maximo / 60
df_agrupado_1.head()

print("""Como podemos observar en los datos arrojados, el dispositivo con el cual se realizan
         un mayor nº de visitas sería con {}, con un total de {} minutos, dando asi un monto total
         de {:.0f} horas""".format(dispositivo_max,tiempo_maximo,tiempo_maximo_2))

#Las edades que suelen pagar más Premium
df_agrupado_2 = df[df["Subscription_Status"] == "Premium"]
df_agrupado_2 = df_agrupado_2.groupby("Age")["duración_vistas"].mean().sort_values(ascending=False).reset_index().round(2)
df_agrupado_2.head()

mayor_edad = df_agrupado_2['Age'].iloc[0]
mayor_tiempo= df_agrupado_2['duración_vistas'].iloc[0]
mayor_tiempo_2 = mayor_tiempo / 60

print(f"""Según esta muestra, las edades que mas suelen pagar premium serían {df_agrupado_2.head(5)}
      siendo la edad que mas paga {mayor_edad} años con un total de minutos de vistas de {mayor_tiempo} minutos
      haciendo un monto total de {mayor_tiempo_2:.2f} horas""")

#El video que tiene más tiempo de reproducción
df_agrupado_3 = df.groupby("Video_ID")["duración_vistas"].sum().sort_values(ascending=False).reset_index().round(2)
df_agrupado_3.head()

video_mas_visto = df_agrupado_3['Video_ID'].iloc[0]
duracion_video = df_agrupado_3['duración_vistas'].iloc[0]
duracion_video_2 = duracion_video / 60

print(f"""El video con mas tiempo de reproducción sería el vide nº {video_mas_visto}
      con un total de {duracion_video} siendo de esta forma un total de {duracion_video_2:.2f} horas,
      por lo que el resultado quedaría de la siguiente forma:\n \n {df_agrupado_3.head(5)}""")

#El género que más le gustó a las mujeres (rating)
df_agrupado_4 = df[df['Gender'] == 'Female']
df_agrupado_4 = df_agrupado_4.groupby(['Gender','Genre'])['Ratings'].sum().sort_values(ascending=False).reset_index()
df_agrupado_4.head()

primer_genero = df_agrupado_4['Gender'].iloc[0]
mayor_rating = df_agrupado_4['Ratings'].iloc[0]

print(f"""Según los datos de esta muestra, el género que más les gustó a las mujeres fue {primer_genero}
      con un total de {mayor_rating} puntaje de rating, lo demás quedaría de la siguiente forma: \n \n {df_agrupado_4.head()}""")


### CONCLUSIÓN SOBRE LOS DATOS ARROJADOS POR LA MUESTRA

Según los datos de esta muestra, el género que más les gustó a las mujeres fue Female
      con un total de 1679 puntaje de rating, lo demás quedaría de la siguiente forma: 
 
    Gender     Genre  Ratings
0  Female    Comedy     1679
1  Female  Thriller     1645
2  Female    Sci-Fi     1616
3  Female    Action     1547
4  Female     Drama     1485
